name: intake-cookbook-dev
channels:
  - conda-forge
dependencies:
  - jupyter-book
  - python
  - jupyterlab
  - jupyter_server<2
  - s3fs
  - intake
  - intake-xarray
  - pip
  - cartopy
  - matplotlib
  - metpy
  - requests
  - aiohttp
  - sphinx-pythia-theme
  - numpy<2
  - pip:
      - intake-markdown
